use super::gap::GapState;
use super::producer::ProducerState;
use super::read::ReadState;
use crate::ProducerMap;
use crate::binding::PartitionFilter;
use crate::log;
use anyhow::Context;
use proto_flow::shuffle;
use proto_gazette::uuid;

/// Immutable slice configuration: topology, bindings, and lazily-initialized
/// journal clients. Set once during Slice startup and never modified.
#[allow(dead_code)]
pub struct Topology {
    /// Unique identifier for this session, generated by the Session actor.
    /// Used as a tracing correlation value for distributed RPCs/logs.
    pub session_id: u32,
    /// Ordered shard topology: each shard owns a disjoint key range.
    pub shards: Vec<shuffle::Shard>,
    /// Index of this Slice RPC within `shards`.
    pub slice_shard_index: u32,
    /// Per-binding shuffle configuration extracted from the task spec.
    pub bindings: Vec<crate::Binding>,
    /// Lazily-initialized Gazette clients for listing and reading journals, indexed by binding.
    pub journal_clients: Vec<super::LazyJournalClient>,
    /// Sorted index for projecting hinted journal names to bindings.
    pub hint_index: HintIndex,
    /// Near-frontier conservative re-read bound "B", in bytes. Applied
    /// consistently to every read the Slice resolves this session.
    pub reread_bound_bytes: u64,
}

/// Flush cycle state machine, tracking in-flight flushes to Log shards.
///
/// The caller is responsible for building the frontier (from reads + causal hints)
/// and passing it to `start`. When a cycle completes, `on_flushed` returns the
/// completed frontier for the caller to reduce into accumulated progress.
///
/// Flush and progress reporting (see `ProgressState`) are deliberately decoupled
/// for latency pipelining: Slices flush autonomously after each commit without
/// waiting for a Session progress request. Multiple flush cycles can complete
/// while the Session processes the previous progress delta. When the Session sends
/// a Progress request, the accumulated flushed frontiers are often already
/// available, reducing end-to-end latency from flush_time + round_trip to
/// approximately max(flush_time, round_trip).
pub struct FlushState {
    /// Monotonically increasing flush cycle number.
    pub cycle: u64,
    /// Whether a commit has been observed since the last flush cycle started.
    ready: bool,
    /// Per-shard in-flight tracking. Non-empty while a cycle is active.
    in_flight: Vec<bool>,
    /// The frontier being flushed in the current cycle.
    flushing: crate::Frontier,
}

impl FlushState {
    pub fn new() -> Self {
        Self {
            cycle: 1,
            ready: false,
            in_flight: Vec::new(),
            flushing: Default::default(),
        }
    }

    /// Whether we're ready to begin a Flush cycle.
    pub fn should_flush(&self) -> bool {
        self.ready && self.in_flight.is_empty()
    }

    /// Record that a commit has been observed (ACK_TXN or OUTSIDE_TXN).
    pub fn set_ready(&mut self) {
        self.ready = true;
    }

    /// Begin a flush cycle with the given pre-built frontier.
    /// Returns the flush cycle number.
    pub fn start(&mut self, shard_count: usize, frontier: crate::Frontier) -> u64 {
        assert!(
            self.in_flight.is_empty(),
            "cannot start flush while one is in-flight"
        );

        self.ready = false;
        self.in_flight.resize(shard_count, true);
        self.flushing = frontier;
        self.cycle
    }

    /// Record a Flushed response from a log shard.
    /// Returns the completed frontier (with per-shard flushed LSNs) when all
    /// shards have flushed.
    pub fn on_flushed(
        &mut self,
        shard_index: usize,
        flushed_lsn: log::Lsn,
    ) -> anyhow::Result<Option<crate::Frontier>> {
        let in_flight = match self.in_flight.get_mut(shard_index) {
            Some(in_flight) if *in_flight => in_flight,
            actual => anyhow::bail!(
                "received Flushed from shard {shard_index} for cycle {} which is not in-flight (actual: {actual:?})",
                self.cycle
            ),
        };

        *in_flight = false;
        let n_pending = self.in_flight.iter().filter(|pending| **pending).count();
        self.flushing.flushed_lsn[shard_index] = flushed_lsn;

        service_kit::event!(
            tracing::Level::DEBUG,
            "log",
            shard_index,
            cycle = self.cycle,
            flushed_lsn = flushed_lsn.as_u64(),
            n_pending,
            "received Flushed response",
        );

        if n_pending != 0 {
            return Ok(None);
        }

        // We increment `cycle` now to ensure we'll clearly reject a duplicate
        // Flushed from a Log (which would be a protocol violation).
        self.in_flight.clear();
        self.cycle += 1;

        Ok(Some(std::mem::take(&mut self.flushing)))
    }
}

/// Progress reporting state, tracking the Session's outstanding progress
/// request and accumulating flushed frontiers until the request is fulfilled.
pub struct ProgressState {
    /// Whether the Session has an outstanding progress request.
    requested: bool,
    /// Accumulated frontier from completed flush cycles, awaiting reporting.
    flushed: crate::Frontier,
}

impl ProgressState {
    pub fn new() -> Self {
        Self {
            requested: false,
            flushed: Default::default(),
        }
    }

    /// Record a Progress request from the Session.
    pub fn request(&mut self) -> anyhow::Result<()> {
        if self.requested {
            anyhow::bail!("received Progress request while one is already pending");
        }
        self.requested = true;
        Ok(())
    }

    /// Reduce a completed flush frontier into accumulated progress.
    pub fn on_flush_completed(&mut self, frontier: crate::Frontier) {
        let (journals, journal_producers, bytes_read_delta, bytes_behind_delta) =
            frontier.measures();

        service_kit::event!(
            tracing::Level::DEBUG,
            "log",
            bytes_behind_delta,
            bytes_read_delta,
            journal_producers,
            journals,
            "gathered Flushed responses",
        );

        self.flushed = std::mem::take(&mut self.flushed).reduce(frontier);
    }

    /// Is progress ready to report? True iff a request is outstanding AND
    /// we've accumulated flushed progress. Idempotent — gate `take_progressed()`
    /// on this so a failed permit reservation can be retried.
    pub fn has_progressed(&self) -> bool {
        self.requested && !self.flushed.journals.is_empty()
    }

    /// Unconditionally clear the outstanding request and accumulated flushed
    /// progress, returning the latter. Callers should gate on `has_progressed()`.
    pub fn take_progressed(&mut self) -> crate::Frontier {
        self.requested = false;
        std::mem::take(&mut self.flushed)
    }
}

impl std::fmt::Debug for FlushState {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.debug_struct("FlushState")
            .field("cycle", &self.cycle)
            .field("ready", &self.ready)
            .field("in_flight", &self.in_flight.iter().filter(|p| **p).count())
            .finish()
    }
}

impl std::fmt::Debug for ProgressState {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.debug_struct("ProgressState")
            .field("requested", &self.requested)
            .field("flushed", &self.flushed.journals.len())
            .finish()
    }
}

/// Result of speculatively sequencing a document.
/// State is not yet committed — the caller must update producer state
/// after successful I/O.
#[derive(Debug)]
pub struct SequencedDoc {
    /// Whether the document should be appended via Log RPCs.
    pub is_append: bool,
    /// Whether this document completed a transaction (triggers flush cycle).
    pub is_commit: bool,
    /// Updated producer state to commit after processing this document.
    pub producer_state: ProducerState,
}

/// Gate on `adjusted_clock` relative to `now`: if the clock is in the future,
/// refresh `now` via `update_now` and re-check. Returns `Some(duration)` if
/// the clock is still ahead after the refresh, or `None` if processing can proceed.
pub fn clock_delay(
    adjusted_clock: &uuid::Clock,
    now: &mut uuid::Clock,
    update_now: impl FnOnce() -> uuid::Clock,
) -> Option<std::time::Duration> {
    if adjusted_clock <= now {
        return None;
    }
    *now = update_now();
    if adjusted_clock <= now {
        return None;
    }
    Some(
        adjusted_clock
            .to_time()
            .duration_since(now.to_time())
            .unwrap_or(std::time::Duration::ZERO),
    )
}

/// Outcome of resolving a StartRead's checkpoint into a main-read start offset,
/// recovered producer state, and any gapped producers.
#[derive(Debug)]
pub struct ResolvedCheckpoint {
    /// `R`: the journal offset at which the main read starts.
    pub offset: i64,
    /// Recovered producer states, all entries included (gapped ones frozen
    /// as-is). This becomes the read's `settled` map.
    pub producers: ProducerMap<ProducerState>,
    /// Producers classified as gapped: an uncommitted begin `F < R`.
    pub gaps: ProducerMap<GapState>,
    /// `M`: the maximum offset magnitude across all producer entries.
    pub max_offset: i64,
}

/// Resolve a StartRead's checkpoint into a start offset, recovered producer
/// state, and gapped producers, per `plans/shuffle-gapped-restart.md`
/// §Restart resolution.
///
/// Let `M = max(|offset|)` across all entries (0 for an empty checkpoint), and
/// `B = reread_bound_bytes`. The main read starts at
/// `R = min({M} ∪ {F : F uncommitted ∧ M - F <= B})`, re-reading at most `B`
/// bytes behind `M`. Each uncommitted span whose begin `F < R` begins before
/// that window and is *gapped*: the main read skips `[F, R)` and the producer
/// is frozen at `F` until a later document resolves it. Committed entries and
/// uncommitted spans with `F >= R` are recovered normally.
///
/// An `offset == 0` entry (a real span at journal start, or a hint-only
/// producer that Frontier reduction has made indistinguishable) is gapped at
/// `F = 0` whenever `R > 0`. This is deliberately conservative: classifying it
/// as normal would risk skipping a real span. It's no worse than today's
/// conservative restart from zero.
///
/// The journal write head is never consulted in place of `M`: bytes between a
/// checkpoint-derived position and the write head may contain transactions no
/// prior session sequenced.
pub fn resolve_checkpoint(
    checkpoint: Vec<shuffle::ProducerFrontier>,
    reread_bound_bytes: u64,
) -> ResolvedCheckpoint {
    let mut producers = ProducerMap::<ProducerState>::with_capacity_and_hasher(
        checkpoint.len(),
        Default::default(),
    );

    // First pass: recover producer states and compute M and the resolved R.
    let mut max_offset = 0i64; // M
    let mut resolved = i64::MAX; // R candidate: min of qualifying uncommitted F.

    for frontier in checkpoint {
        let shuffle::ProducerFrontier {
            producer,
            last_commit,
            hinted_commit: _,
            offset,
        } = frontier;

        let producer = uuid::Producer::from_i64(producer);
        let last_commit = uuid::Clock::from_u64(last_commit);

        max_offset = max_offset.max(offset.abs());

        producers.insert(
            producer,
            ProducerState {
                last_commit,
                max_continue: uuid::Clock::zero(),
                offset,
            },
        );
    }

    // Second pass over producers to find R now that M is known: the minimum
    // uncommitted begin within B bytes of M (else M itself). `M - F` is
    // non-negative because M is the maximum magnitude.
    for ps in producers.values() {
        if ps.offset >= 0 && (max_offset - ps.offset) as u64 <= reread_bound_bytes {
            resolved = resolved.min(ps.offset);
        }
    }
    let offset = resolved.min(max_offset); // R.

    // Third pass: classify uncommitted spans beginning before R as gapped.
    let mut gaps = ProducerMap::<GapState>::with_capacity_and_hasher(0, Default::default());
    for (producer, ps) in producers.iter() {
        if ps.offset >= 0 && ps.offset < offset {
            gaps.insert(
                *producer,
                GapState::Gapped {
                    gap_begin: ps.offset,
                },
            );
        }
    }

    ResolvedCheckpoint {
        offset,
        producers,
        gaps,
        max_offset,
    }
}

/// Outcome of classifying a main-read document against a *gapped* producer's
/// frozen state (`plans/shuffle-gapped-restart.md` §Main-read outcomes).
///
/// A gapped producer's frozen `max_continue == 0` makes `uuid::sequence`
/// misclassify the rollback rows as `AckDuplicate`, so gapped documents are
/// classified here instead of through `sequence_document`.
#[derive(Debug, PartialEq, Eq)]
pub enum GappedOutcome {
    /// CONTINUE with `clock > last_commit`: suppress, with no state mutation
    /// and no append. The pinned `F` must not be overwritten.
    Suppress,
    /// A duplicate at or below `last_commit` (CONTINUE or OUTSIDE): drop and
    /// retain the gap.
    Drop,
    /// ACK with `clock > last_commit`: park the main read and begin backfill.
    TriggerBackfill,
    /// ACK with `clock == last_commit`: durable clean rollback. Discard the
    /// gap and emit committed progress `offset = -ack_end`.
    CleanRollback,
    /// ACK with `clock < last_commit`: durable deep rollback (no backfill).
    /// Discard the gap, warn, regress `last_commit` to the ACK clock, and emit
    /// `offset = -ack_end`.
    DeepRollback,
    /// OUTSIDE with `clock > last_commit`: discard the gap, then re-process the
    /// document through the normal sequencing path.
    OutsideResolve,
}

/// Classify a main-read document of a gapped producer against its frozen
/// recovered `last_commit`. Pure function; the caller applies the outcome.
///
/// See the normative outcome table in `plans/shuffle-gapped-restart.md`
/// §Main-read outcomes while gapped.
pub fn sequence_gapped(gap_last_commit: uuid::Clock, meta: &super::read::Meta) -> GappedOutcome {
    let super::read::Meta { clock, flags, .. } = meta;

    if flags.is_outside() {
        if *clock > gap_last_commit {
            GappedOutcome::OutsideResolve
        } else {
            GappedOutcome::Drop
        }
    } else if flags.is_continue() {
        if *clock > gap_last_commit {
            GappedOutcome::Suppress
        } else {
            GappedOutcome::Drop
        }
    } else {
        // ACK: the gap proves a pending span exists, so an ACK at or below
        // last_commit rolls it back (rather than the `AckDuplicate` that frozen
        // `max_continue == 0` would otherwise yield).
        match clock.cmp(&gap_last_commit) {
            std::cmp::Ordering::Greater => GappedOutcome::TriggerBackfill,
            std::cmp::Ordering::Equal => GappedOutcome::CleanRollback,
            std::cmp::Ordering::Less => GappedOutcome::DeepRollback,
        }
    }
}

/// Speculatively sequence a document against current producer state.
///
/// Returns a `SequencedDoc` capturing the outcome. State is NOT modified;
/// the caller must update producer state after successful I/O.
pub fn sequence_document(
    read_state: &ReadState,
    binding: &crate::Binding,
    meta: &super::read::Meta,
) -> anyhow::Result<SequencedDoc> {
    // Query for the Producer's latest state: pending
    // (updated since last flush) takes precedence over settled state.
    let producer_state = (read_state.pending.get(&meta.producer))
        .or_else(|| read_state.settled.get(&meta.producer))
        .cloned() // This is a cheap clone.
        .unwrap_or_default();

    sequence_producer(producer_state, &read_state.journal, binding, meta)
}

/// Speculatively sequence a document against an explicit `producer_state`.
///
/// The core of `sequence_document`, factored out so the backfill path can
/// sequence historical target-producer documents against a gap's `live` state
/// (never `pending`/`settled`). State is NOT modified; the caller commits the
/// returned `producer_state` after successful I/O.
pub fn sequence_producer(
    mut producer_state: ProducerState,
    journal: &str,
    binding: &crate::Binding,
    meta: &super::read::Meta,
) -> anyhow::Result<SequencedDoc> {
    let super::read::Meta {
        producer,
        clock,
        flags,
        begin_offset,
        end_offset,
    } = meta;

    // Determine the message's sequencing outcome.
    let outcome = uuid::sequence(
        *flags,
        *clock,
        &mut producer_state.last_commit,
        &mut producer_state.max_continue,
    )
    .with_context(|| {
        format!(
            "failed to sequence journal {} (binding {}) document at offset {begin_offset} \
            (producer {producer:?} with clock {clock:?}, last_commit {:?}, max_continue {:?})",
            journal,
            binding.state_key(),
            producer_state.last_commit,
            producer_state.max_continue,
        )
    })?;

    // Match over `outcome` to update `producer_state` and determine append/commit.
    let (is_append, is_commit) = match outcome {
        uuid::SequenceOutcome::OutsideCommit => {
            producer_state.offset = -*end_offset;
            (true, true)
        }
        uuid::SequenceOutcome::OutsideDuplicate => (false, false),
        uuid::SequenceOutcome::ContinueBeginSpan => {
            producer_state.offset = *begin_offset;
            (true, false)
        }
        uuid::SequenceOutcome::ContinueExtendSpan => (true, false),
        uuid::SequenceOutcome::ContinueDuplicate => (false, false),
        uuid::SequenceOutcome::AckDeepRollback => {
            tracing::warn!(
                binding=%binding.state_key(),
                clock=?clock,
                journal=%journal,
                last_commit=?producer_state.last_commit,
                producer=?producer,
                "detected rollback prior to last committed clock of the producer (possible loss of exactly-once guarantees)",
            );
            producer_state.offset = -*end_offset;
            (false, true)
        }
        uuid::SequenceOutcome::AckCommit
        | uuid::SequenceOutcome::AckEmpty
        | uuid::SequenceOutcome::AckCleanRollback => {
            // This ACK commits (or rolls back) the producer's preceding
            // CONTINUE_TXN documents in this journal only. Cross-journal
            // visibility for the same producer transaction is handled separately
            // via `extract_causal_hints`.
            producer_state.offset = -*end_offset;
            (false, true)
        }
        uuid::SequenceOutcome::AckDuplicate => (false, false),
    };

    // A `notBefore` or `notAfter` suppresses document append, but doesn't impact
    // the propagation of flush and progress reporting.
    let is_append = is_append && *clock >= binding.not_before && *clock < binding.not_after;

    tracing::trace!(
        journal = %journal,
        binding = binding.state_key(),
        ?producer,
        ?clock,
        begin_offset,
        ?outcome,
        is_append,
        is_commit,
        "sequenced document"
    );

    Ok(SequencedDoc {
        is_append,
        is_commit,
        producer_state,
    })
}

/// Sorted index for projecting hinted journal names to (binding_index, cohort),
/// with per-entry partition filters.
///
/// Entries are sorted by prefix then binding index. Because the control plane
/// guarantees no collection is a prefix of another, at most one distinct prefix
/// can match a given journal name — so lookup is a single binary search plus
/// a linear scan of adjacent entries sharing that prefix.
///
/// Hints are filtered to the ACK's cohort because cohorts (unique (priority,
/// read_delay) tuples) have independent visibility semantics. If a producer
/// writes to journals spanning multiple read cohorts within one of its transactions,
/// we only want to gate progress on reading commits from journals matching
/// the ACK's cohort.
///
/// If we didn't filter in this way, then progress of a journal read in real-time
/// could be blocked by the read-delay applied to a hinted journal. Or similarly,
/// a high-priority journal could be blocked by a low-priority hinted journal.
///
/// Hinted journals of other cohorts will have their own ACKs, and will project to
/// hints internal to their own cohort's progress tracking.
pub struct HintIndex {
    /// (prefix, binding_index, cohort, filter), sorted by (prefix, binding_index).
    entries: Vec<(Box<str>, u16, u32, PartitionFilter)>,
    /// True if some cohort reads one journal-prefix under multiple bindings — so a
    /// journal may be read by ≥2 bindings of a cohort. When false (the common case
    /// where each journal maps 1:1 to a binding), `extract_causal_hints` skips
    /// same-cohort self-hint projection, paying only a boolean test per ACK.
    cohort_shares_journal: bool,
}

impl HintIndex {
    pub fn new<'a>(entries: impl Iterator<Item = (&'a str, u16, u32, PartitionFilter)>) -> Self {
        let mut index: Vec<(&str, u16, u32, PartitionFilter)> = entries.collect();

        index.sort_by(|a, b| a.0.cmp(&b.0).then(a.1.cmp(&b.1)));

        // A cohort reads a journal under multiple bindings iff two entries share a
        // (prefix, cohort). We can't rely on the (prefix, binding) sort to make
        // such a pair adjacent: a binding of a different cohort on the same prefix
        // can sort between them. For example priorities `[0, 1, 0]` assign cohorts
        // `[0, 1, 0]`, where bindings 0 and 2 share cohort 0 but binding 1 sorts
        // between them. Detect any duplicate (prefix, cohort) regardless of order.
        // This is conservative — `lookup`'s partition filter still scopes self-hints
        // to bindings that actually read a given journal — but it cheaply clears the
        // common 1:1 case.
        let mut seen_prefix_cohort = std::collections::HashSet::new();
        let cohort_shares_journal = index
            .iter()
            .any(|(prefix, _, cohort, _)| !seen_prefix_cohort.insert((*prefix, *cohort)));

        // Now that we've sorted, re-allocate partition name prefixes.
        // This ensures aligns memory locality and ordering with our query pattern.
        let entries: Vec<(Box<str>, u16, u32, PartitionFilter)> = index
            .into_iter()
            .map(|(prefix, idx, cohort, filter)| (Box::from(prefix), idx, cohort, filter))
            .collect();

        Self {
            entries,
            cohort_shares_journal,
        }
    }

    pub fn from_bindings(bindings: &[crate::Binding]) -> Self {
        Self::new(bindings.iter().map(|b| {
            (
                b.partition_prefix.as_ref(),
                b.index,
                b.cohort,
                PartitionFilter::new(&b.partition_fields, &b.partition_selector),
            )
        }))
    }

    /// Find all binding indices whose prefix matches `journal` within `cohort`,
    /// filtering by each entry's partition selector.
    ///
    /// Because no collection prefix is a prefix of another, there is at most
    /// one matching prefix for any journal name.
    pub fn lookup(&self, journal: &str, cohort: u32, out: &mut Vec<u16>) -> anyhow::Result<()> {
        out.clear();

        // Find the first entry whose partition name prefix is > journal.
        // The matching prefix, if any, is immediately before this position.
        let pos = self
            .entries
            .partition_point(|(prefix, _, _, _)| prefix.as_ref() <= journal);
        if pos == 0 {
            return Ok(());
        }

        // Check whether the entry just before `pos` is a prefix of `journal`.
        let matched_prefix = &self.entries[pos - 1].0;
        if !journal.starts_with(matched_prefix.as_ref()) {
            return Ok(());
        }

        // Scan all entries sharing this prefix (they are contiguous and sorted).
        for &(ref prefix, binding_idx, binding_cohort, ref filter) in
            self.entries[..pos].iter().rev()
        {
            if prefix != matched_prefix {
                break;
            }
            if binding_cohort == cohort
                && filter.matches_name_suffix(&journal[matched_prefix.len()..])?
            {
                out.push(binding_idx);
            }
        }

        Ok(())
    }
}

/// Decode causal hints from an ACK document and project them through the
/// `hint_index` into `causal_hints` entries keyed by (journal, binding_index).
pub fn extract_causal_hints<N: json::AsNode>(
    hint_index: &HintIndex,
    ack_journal: &str,
    ack_cohort: u32,
    ack_binding_index: u16,
    ack_producer: uuid::Producer,
    ack_clock: uuid::Clock,
    ack_doc: &N,
    causal_hints: &mut super::CausalHints,
) -> anyhow::Result<()> {
    let mut hint_iter =
        publisher::intents::decode_transaction_hints(ack_journal, ack_producer, ack_clock, ack_doc);
    let mut matched_bindings = Vec::new();

    while let Some(result) = hint_iter.next() {
        let (hinted_journal, hinted_producer, hinted_clock) = result.map_err(|err| {
            anyhow::anyhow!("decoding causal hint from ACK in {ack_journal}: {err}")
        })?;

        hint_index.lookup(hinted_journal, ack_cohort, &mut matched_bindings)?;

        for &binding_idx in &matched_bindings {
            causal_hints
                .entry((hinted_journal.into(), binding_idx))
                .or_default()
                .push((hinted_producer, hinted_clock));
        }
    }

    // An ACK doc carries hints only for *other* journals, but one journal may
    // be read by multiple bindings of a cohort. Project a self-hint from this
    // ACK's own (journal, producer) to the *other* cohort bindings reading the
    // journal, so checkpoint visibility is held until all have read through the
    // producer's commit. Skipped unless a cohort actually shares a journal
    // across bindings.
    if hint_index.cohort_shares_journal {
        hint_index.lookup(ack_journal, ack_cohort, &mut matched_bindings)?;

        for &binding_idx in &matched_bindings {
            if binding_idx == ack_binding_index {
                continue;
            }
            causal_hints
                .entry((ack_journal.into(), binding_idx))
                .or_default()
                .push((ack_producer, ack_clock));
        }
    }

    Ok(())
}

#[cfg(test)]
mod test {
    use super::super::CausalHints;
    use super::super::read::Meta;
    use super::*;
    use crate::testing::test_binding;
    use proto_gazette::broker;
    use proto_gazette::uuid::{Clock, Flags, Producer};

    const OUTSIDE: Flags = Flags(proto_gazette::message_flags::OUTSIDE_TXN as u16);
    const CONTINUE: Flags = Flags(proto_gazette::message_flags::CONTINUE_TXN as u16);
    const ACK: Flags = Flags(proto_gazette::message_flags::ACK_TXN as u16);

    fn meta(
        producer: Producer,
        clock: Clock,
        flags: Flags,
        begin_offset: i64,
        end_offset: i64,
    ) -> Meta {
        Meta {
            producer,
            clock,
            flags,
            begin_offset,
            end_offset,
        }
    }

    fn producer(id: u8) -> Producer {
        Producer::from_bytes([id | 0x01, 0, 0, 0, 0, 0])
    }

    /// Build a checkpoint entry for a producer with zero clocks and a committed offset.
    /// This is the minimal "known producer" state needed by tests.
    fn checkpoint_entry(p: &Producer, committed_end: i64) -> shuffle::ProducerFrontier {
        shuffle::ProducerFrontier {
            producer: p.as_i64(),
            last_commit: 0,
            hinted_commit: 0,
            offset: -committed_end, // Negative = committed end offset.
        }
    }

    struct TestState {
        bindings: Vec<crate::Binding>,
        reads: Vec<ReadState>,
        flush: FlushState,
        progress: ProgressState,
    }

    fn test_state(bindings: Vec<crate::Binding>) -> TestState {
        TestState {
            bindings,
            reads: Vec::new(),
            flush: FlushState::new(),
            progress: ProgressState::new(),
        }
    }

    impl TestState {
        fn commit(&mut self, read_id: usize, producer: Producer, seq: SequencedDoc) {
            _ = self.reads[read_id]
                .pending
                .insert(producer, seq.producer_state);
            if seq.is_commit {
                self.flush.set_ready();
            }
        }
    }

    fn cp(p: &Producer, offset: i64) -> shuffle::ProducerFrontier {
        shuffle::ProducerFrontier {
            producer: p.as_i64(),
            last_commit: Clock::from_u64(100).as_u64(),
            hinted_commit: 0,
            offset,
        }
    }

    /// Sorted (F, is_gapped) tuple per producer, for stable assertions.
    fn gap_summary(r: &ResolvedCheckpoint) -> Vec<(i64, bool)> {
        let mut out: Vec<(i64, bool)> = r
            .producers
            .iter()
            .map(|(p, ps)| (ps.offset, r.gaps.contains_key(p)))
            .collect();
        out.sort();
        out
    }

    #[test]
    fn test_resolve_checkpoint() {
        let p1 = producer(0x01);
        let p3 = producer(0x03);
        let p5 = producer(0x05);

        // Empty checkpoint → M = R = 0, no gaps.
        let r = resolve_checkpoint(vec![], 0);
        assert_eq!((r.offset, r.max_offset), (0, 0));
        assert!(r.producers.is_empty() && r.gaps.is_empty());

        // All committed: M = max magnitude, R = M (no uncommitted), no gaps.
        let r = resolve_checkpoint(vec![cp(&p1, -500), cp(&p3, -1000)], 0);
        assert_eq!((r.offset, r.max_offset), (1000, 1000));
        assert!(r.gaps.is_empty());

        // Mixed, B = 0: R = M = 1000 (max magnitude, from the committed -1000);
        // both uncommitted spans (300, 100) begin before R → gapped.
        let r = resolve_checkpoint(vec![cp(&p1, -1000), cp(&p3, 300), cp(&p5, 100)], 0);
        assert_eq!((r.offset, r.max_offset), (1000, 1000));
        assert_eq!(
            gap_summary(&r),
            vec![(-1000, false), (100, true), (300, true)]
        );

        // Same checkpoint, B large enough to include the nearest uncommitted
        // (M - 300 = 700 <= B) but not the far one (M - 100 = 900 > B): R = 300,
        // p3 (F=300 >= R) normal, p5 (F=100 < R) gapped.
        let r = resolve_checkpoint(vec![cp(&p1, -1000), cp(&p3, 300), cp(&p5, 100)], 700);
        assert_eq!(r.offset, 300);
        assert_eq!(
            gap_summary(&r),
            vec![(-1000, false), (100, true), (300, false)]
        );

        // Unbounded B degenerates to min-uncommitted-begin: R = 100, no gaps.
        let r = resolve_checkpoint(vec![cp(&p1, -1000), cp(&p3, 300), cp(&p5, 100)], u64::MAX);
        assert_eq!(r.offset, 100);
        assert!(r.gaps.is_empty());

        // offset == 0 with R > 0 is conservatively gapped at F = 0.
        let r = resolve_checkpoint(vec![cp(&p1, 0), cp(&p3, 500)], 0);
        assert_eq!((r.offset, r.max_offset), (500, 500));
        assert_eq!(gap_summary(&r), vec![(0, true), (500, false)]);

        // offset == 0 with R == 0 (empty of committed/near spans) is NOT gapped:
        // the sole span begins at journal start and the main read covers it.
        let r = resolve_checkpoint(vec![cp(&p1, 0)], u64::MAX);
        assert_eq!((r.offset, r.max_offset), (0, 0));
        assert!(r.gaps.is_empty());
    }

    #[test]
    fn test_sequence_gapped_outcome_table() {
        use GappedOutcome::*;
        let lc = Clock::from_u64(100);
        let p = producer(0x01);

        // (flags, clock, expected) — the complete normative outcome table for a
        // gapped producer's main-read documents (spec §Main-read outcomes).
        let cases: &[(Flags, u64, GappedOutcome)] = &[
            (CONTINUE, 150, Suppress),      // ContinueBeginSpan
            (CONTINUE, 100, Drop),          // ContinueDuplicate (== last_commit)
            (CONTINUE, 50, Drop),           // ContinueDuplicate (< last_commit)
            (ACK, 150, TriggerBackfill),    // AckEmpty → park + backfill
            (ACK, 100, CleanRollback),      // AckDuplicate → durable clean rollback
            (ACK, 50, DeepRollback),        // AckDuplicate → durable deep rollback
            (OUTSIDE, 150, OutsideResolve), // OutsideCommit → discard gap, reprocess
            (OUTSIDE, 100, Drop),           // OutsideDuplicate (== last_commit)
            (OUTSIDE, 50, Drop),            // OutsideDuplicate (< last_commit)
        ];
        for (flags, clock, expected) in cases {
            let m = meta(p, Clock::from_u64(*clock), *flags, 0, 10);
            assert_eq!(
                sequence_gapped(lc, &m),
                *expected,
                "flags={flags:?} clock={clock}",
            );
        }
    }

    #[test]
    fn test_gapped_rollback_is_durable() {
        // A gapped clean/deep rollback emits a committed entry (offset =
        // -ack_end). Re-resolving that checkpoint must not recreate the gap
        // (spec correctness property 5), even when other producers raise M.
        let p = producer(0x01);
        let p2 = producer(0x03);

        let r = resolve_checkpoint(vec![cp(&p, -450)], 0);
        assert!(r.gaps.is_empty(), "committed offset is never gapped");

        let r = resolve_checkpoint(vec![cp(&p, -450), cp(&p2, -100_000)], 0);
        assert!(
            !r.gaps.contains_key(&p),
            "rolled-back producer stays committed across restart",
        );
    }

    #[test]
    fn test_backfill_intermediate_commit_is_detected() {
        // The backfill drain path sequences target-producer documents against
        // the gap's `live` state and bails when `sequence_producer` reports a
        // commit — a distinct committing ACK inside the historical range
        // contradicts the recovered checkpoint (spec §One-transaction invariant).
        let binding = test_binding(0, true, None, "/suffix");
        let p = producer(0x01);

        let live = ProducerState {
            last_commit: Clock::from_u64(100),
            max_continue: Clock::zero(),
            offset: 200,
        };
        // A CONTINUE extends the reconstructed span — not a commit.
        let s = sequence_producer(
            live,
            "test/journal",
            &binding,
            &meta(p, Clock::from_u64(150), CONTINUE, 200, 210),
        )
        .unwrap();
        assert!(!s.is_commit, "CONTINUE within the range is not a commit");

        // A committing ACK within the range reports is_commit; the actor treats
        // this as a terminal consistency error and bails.
        let s2 = sequence_producer(
            s.producer_state,
            "test/journal",
            &binding,
            &meta(p, Clock::from_u64(150), ACK, 210, 220),
        )
        .unwrap();
        assert!(
            s2.is_commit,
            "a committing ACK inside the range is detectable (actor bails)",
        );
    }

    #[test]
    fn test_sequence_not_before_not_after() {
        let mut bindings = vec![test_binding(0, true, None, "/suffix")];
        bindings[0].not_before = Clock::from_u64(100);
        bindings[0].not_after = Clock::from_u64(500);

        let mut s = test_state(bindings);

        let p1 = producer(0x01);

        // Start read with p1 in the checkpoint.
        let producers = resolve_checkpoint(vec![checkpoint_entry(&p1, 0)], u64::MAX).producers;
        s.reads.push(ReadState {
            binding_index: 0,
            journal: "test/journal/A".into(),
            settled: producers,
            pending: Default::default(),
            gaps: Default::default(),
            read_offset: 0,
            prev_read_offset: 0,
            write_head: 0,
            prev_write_head: 0,
        });

        // Clock before notBefore: suppresses append but not commit.
        let seq = sequence_document(
            &s.reads[0],
            &s.bindings[0],
            &meta(p1, Clock::from_u64(50), OUTSIDE, 0, 50),
        )
        .unwrap();
        assert!(!seq.is_append, "before notBefore → no append");
        assert!(seq.is_commit, "before notBefore → commit still propagates");
        s.commit(0, p1, seq);

        // Clock within range: normal append.
        let seq = sequence_document(
            &s.reads[0],
            &s.bindings[0],
            &meta(p1, Clock::from_u64(200), OUTSIDE, 50, 100),
        )
        .unwrap();
        assert!(seq.is_append, "within range → append");
        assert!(seq.is_commit, "within range → commit");
        s.commit(0, p1, seq);

        // Clock at notAfter boundary: suppresses append (notAfter is exclusive).
        let seq = sequence_document(
            &s.reads[0],
            &s.bindings[0],
            &meta(p1, Clock::from_u64(500), OUTSIDE, 100, 150),
        )
        .unwrap();
        assert!(!seq.is_append, "at notAfter → no append");
        assert!(seq.is_commit, "at notAfter → commit still propagates");
    }

    #[test]
    fn test_flush_state_machine() {
        let mut s = test_state(vec![test_binding(0, true, None, "/suffix")]);

        let p1 = producer(0x01);
        let p3 = producer(0x03);

        // Start read with both producers in the checkpoint.
        let producers = resolve_checkpoint(
            vec![checkpoint_entry(&p1, 0), checkpoint_entry(&p3, 0)],
            u64::MAX,
        )
        .producers;
        s.reads.push(ReadState {
            binding_index: 0,
            journal: "test/journal/A".into(),
            settled: producers,
            pending: Default::default(),
            gaps: Default::default(),
            read_offset: 0,
            prev_read_offset: 0,
            write_head: 0,
            prev_write_head: 0,
        });

        // Initially: flush not ready → should_flush false.
        assert!(!s.flush.should_flush());

        // Sequence an OUTSIDE commit (sets flush ready via commit_enqueue).
        let seq = sequence_document(
            &s.reads[0],
            &s.bindings[0],
            &meta(p1, Clock::from_unix(100, 0), OUTSIDE, 0, 50),
        )
        .unwrap();
        s.commit(0, p1, seq);

        // Now should_flush is true.
        assert!(s.flush.should_flush());

        // Add a second producer's document for richer frontier.
        let seq = sequence_document(
            &s.reads[0],
            &s.bindings[0],
            &meta(p3, Clock::from_unix(200, 0), OUTSIDE, 50, 100),
        )
        .unwrap();
        s.commit(0, p3, seq);

        // Build frontier and start flush with 3 shards.
        let frontier =
            super::super::producer::build_flush_frontier(&mut s.reads, std::iter::empty(), 3);
        assert!(!frontier.journals.is_empty(), "flushing frontier built");

        let flush_cycle = s.flush.start(3, frontier);
        assert_eq!(flush_cycle, 1, "flush_cycle is the current cycle");
        assert!(!s.flush.should_flush(), "not ready after start");
        assert!(s.reads[0].pending.is_empty(), "pending drained to settled");

        // Partial flushed: still in flight.
        assert!(
            s.flush
                .on_flushed(0, log::Lsn::new(0, 100))
                .unwrap()
                .is_none(),
            "still in flight after 1/3"
        );
        assert!(
            s.flush
                .on_flushed(2, log::Lsn::new(0, 300))
                .unwrap()
                .is_none(),
            "still in flight after 2/3"
        );

        // All flushed: returns completed frontier. Cycle advances so that
        // a duplicate Flushed with the old cycle is rejected as a protocol violation.
        let completed = s
            .flush
            .on_flushed(1, log::Lsn::new(0, 200))
            .unwrap()
            .expect("all flushed");

        assert_eq!(
            s.flush.cycle, 2,
            "cycle incremented after all shards flushed"
        );
        s.progress.on_flush_completed(completed);

        insta::assert_debug_snapshot!("flush_state_machine", &s.progress.flushed);
    }

    #[test]
    fn test_progress_reporting() {
        let mut progress = ProgressState::new();

        // No request + no flushed → not ready.
        assert!(!progress.has_progressed());

        // Request but no flushed → not ready.
        progress.request().unwrap();
        assert!(!progress.has_progressed());
        // requested should remain true.
        assert!(progress.requested);

        // Populate flushed directly for this test.
        progress.flushed = crate::Frontier {
            journals: vec![crate::JournalFrontier {
                journal: "test/journal/A".into(),
                binding: 0,
                producers: vec![crate::ProducerFrontier {
                    producer: producer(0x01),
                    last_commit: Clock::from_u64(100),
                    hinted_commit: Clock::from_u64(0),
                    offset: -500,
                }],
                bytes_read_delta: 0,
                bytes_behind_delta: 0,
            }],
            flushed_lsn: vec![],
            unresolved_hints: 0,
        };

        // Request + flushed → has_progressed gates, take_progressed consumes.
        assert!(progress.has_progressed());
        let frontier = progress.take_progressed();
        assert!(!progress.requested, "requested cleared");
        assert!(progress.flushed.journals.is_empty(), "flushed cleared");
        assert_eq!(frontier.journals.len(), 1);

        // Double request is an error.
        progress.request().unwrap();
        let err = progress.request().unwrap_err();
        assert!(
            format!("{err}").contains("already pending"),
            "expected double-request error, got: {err}"
        );
    }

    #[test]
    fn test_clock_delay() {
        let mut now = Clock::from_unix(100, 0);

        // Clock in the past: no delay, update_now not called.
        let past = Clock::from_unix(50, 0);
        assert!(clock_delay(&past, &mut now, || panic!("should not refresh")).is_none());

        // Clock equal to now: no delay.
        let equal = Clock::from_unix(100, 0);
        assert!(clock_delay(&equal, &mut now, || panic!("should not refresh")).is_none());

        // Clock in the future, but refresh catches up: no delay.
        let future1 = Clock::from_unix(110, 0);
        assert!(clock_delay(&future1, &mut now, || Clock::from_unix(110, 0)).is_none());
        assert_eq!(now, Clock::from_unix(110, 0), "now was refreshed");

        // Clock in the future even after refresh: returns remaining delay.
        let future2 = Clock::from_unix(120, 0);
        let delay = clock_delay(&future2, &mut now, || Clock::from_unix(115, 0)).unwrap();
        assert_eq!(delay, std::time::Duration::from_secs(5));
        assert_eq!(now, Clock::from_unix(115, 0), "now was refreshed");
    }

    /// Tests the offset tracking and is_enqueue/is_commit disposition that
    /// sequence_document layers on top of uuid::sequence (which has its own
    /// exhaustive tests for clock state transitions).
    #[test]
    fn test_sequence_offset_and_disposition() {
        let bindings = vec![test_binding(0, true, None, "/suffix")];
        let mut s = test_state(bindings);

        let p1 = producer(0x01);

        let producers = resolve_checkpoint(vec![checkpoint_entry(&p1, 0)], u64::MAX).producers;
        s.reads.push(ReadState {
            binding_index: 0,
            journal: "test/journal/A".into(),
            settled: producers,
            pending: Default::default(),
            gaps: Default::default(),
            read_offset: 0,
            prev_read_offset: 0,
            write_head: 0,
            prev_write_head: 0,
        });

        // ContinueBeginSpan: enqueued, no commit, offset set to begin_offset.
        let seq = sequence_document(
            &s.reads[0],
            &s.bindings[0],
            &meta(p1, Clock::from_unix(10, 0), CONTINUE, 100, 150),
        )
        .unwrap();
        assert!(seq.is_append);
        assert!(!seq.is_commit);
        assert_eq!(
            seq.producer_state.offset, 100,
            "offset = begin of uncommitted span"
        );
        s.commit(0, p1, seq);

        // ContinueExtendSpan: enqueued, no commit, offset preserved from BeginSpan.
        let seq = sequence_document(
            &s.reads[0],
            &s.bindings[0],
            &meta(p1, Clock::from_unix(20, 0), CONTINUE, 150, 200),
        )
        .unwrap();
        assert!(seq.is_append);
        assert!(!seq.is_commit);
        assert_eq!(seq.producer_state.offset, 100, "offset unchanged on extend");
        s.commit(0, p1, seq);

        // ContinueDuplicate: filtered out entirely.
        let seq = sequence_document(
            &s.reads[0],
            &s.bindings[0],
            &meta(p1, Clock::from_unix(15, 0), CONTINUE, 200, 250),
        )
        .unwrap();
        assert!(!seq.is_append);
        assert!(!seq.is_commit);

        // AckCommit: not enqueued, triggers commit/flush, offset becomes committed.
        let seq = sequence_document(
            &s.reads[0],
            &s.bindings[0],
            &meta(p1, Clock::from_unix(20, 0), ACK, 250, 300),
        )
        .unwrap();
        assert!(!seq.is_append, "ACKs are never appended");
        assert!(seq.is_commit, "AckCommit triggers flush");
        assert_eq!(
            seq.producer_state.offset, -300,
            "offset = negated committed end"
        );
        s.commit(0, p1, seq);

        // AckDuplicate: no append, no commit (no spurious flush).
        let seq = sequence_document(
            &s.reads[0],
            &s.bindings[0],
            &meta(p1, Clock::from_unix(20, 0), ACK, 300, 350),
        )
        .unwrap();
        assert!(!seq.is_append);
        assert!(!seq.is_commit, "AckDuplicate must not trigger flush");

        // Start a new CONTINUE span, then clean rollback (ACK at last_commit clock).
        let seq = sequence_document(
            &s.reads[0],
            &s.bindings[0],
            &meta(p1, Clock::from_unix(30, 0), CONTINUE, 350, 400),
        )
        .unwrap();
        assert!(seq.is_append);
        assert_eq!(seq.producer_state.offset, 350, "new span begin");
        s.commit(0, p1, seq);

        let seq = sequence_document(
            &s.reads[0],
            &s.bindings[0],
            &meta(p1, Clock::from_unix(20, 0), ACK, 400, 450),
        )
        .unwrap();
        assert!(!seq.is_append);
        assert!(seq.is_commit, "AckCleanRollback triggers flush");
        assert_eq!(
            seq.producer_state.offset, -450,
            "rollback yields committed offset"
        );
    }

    /// Build a passthrough PartitionFilter that accepts any value for the given fields.
    /// The field count must match the partition field segments in the journal suffix.
    fn passthrough_filter(fields: &[&str]) -> PartitionFilter {
        let fields: Vec<String> = fields.iter().map(|f| f.to_string()).collect();
        PartitionFilter::new(&fields, &broker::LabelSelector::default())
    }

    #[test]
    fn test_hint_index_lookup() {
        // Example filter that includes "alpha" category and excludes "bad" region.
        let filter = PartitionFilter::new(
            &["category".to_string(), "region".to_string()],
            &broker::LabelSelector {
                include: Some(labels::build_set(
                    [(
                        "estuary.dev/field/category".to_string(),
                        "alpha".to_string(),
                    )]
                    .into_iter(),
                )),
                exclude: Some(labels::build_set(
                    [("estuary.dev/field/region".to_string(), "bad".to_string())].into_iter(),
                )),
            },
        );

        let cases: Vec<(Vec<(&str, u16, u32, PartitionFilter)>, &str, u32, Vec<u16>)> = vec![
            // Prefix match: anvils has 1 partition field, bananas has 0.
            (
                vec![
                    ("acmeCo/anvils/", 0, 0, passthrough_filter(&["part"])),
                    ("acmeCo/bananas/", 1, 0, passthrough_filter(&[])),
                ],
                "acmeCo/anvils/part=a/pivot=00",
                0,
                vec![0],
            ),
            (
                vec![
                    ("acmeCo/anvils/", 0, 0, passthrough_filter(&["part"])),
                    ("acmeCo/bananas/", 1, 0, passthrough_filter(&[])),
                ],
                "acmeCo/bananas/pivot=00",
                0,
                vec![1],
            ),
            // No matching prefix.
            (
                vec![
                    ("acmeCo/anvils/", 0, 0, passthrough_filter(&["part"])),
                    ("acmeCo/bananas/", 1, 0, passthrough_filter(&[])),
                ],
                "other/collection/pivot=00",
                0,
                vec![],
            ),
            // Cohort filtering: same prefix, different cohorts.
            (
                vec![
                    ("acmeCo/anvils/", 0, 0, passthrough_filter(&["part"])),
                    ("acmeCo/anvils/", 1, 1, passthrough_filter(&["part"])),
                ],
                "acmeCo/anvils/part=a/pivot=00",
                0,
                vec![0],
            ),
            (
                vec![
                    ("acmeCo/anvils/", 0, 0, passthrough_filter(&["part"])),
                    ("acmeCo/anvils/", 1, 1, passthrough_filter(&["part"])),
                ],
                "acmeCo/anvils/part=a/pivot=00",
                1,
                vec![1],
            ),
            // Unknown cohort.
            (
                vec![
                    ("acmeCo/anvils/", 0, 0, passthrough_filter(&["part"])),
                    ("acmeCo/anvils/", 1, 1, passthrough_filter(&["part"])),
                ],
                "acmeCo/anvils/part=a/pivot=00",
                99,
                vec![],
            ),
            // Multiple bindings, same prefix and cohort.
            (
                vec![
                    ("acmeCo/anvils/", 0, 0, passthrough_filter(&["part"])),
                    ("acmeCo/anvils/", 1, 0, passthrough_filter(&["part"])),
                ],
                "acmeCo/anvils/part=a/pivot=00",
                0,
                vec![0, 1],
            ),
            // Partition filter: "alpha" is included, "eu" not excluded.
            (
                vec![("acmeCo/anvils/", 0, 0, filter.clone())],
                "acmeCo/anvils/category=alpha/region=eu/pivot=00",
                0,
                vec![0],
            ),
            // Partition filter: "beta" is not included, "eu" not excluded.
            (
                vec![("acmeCo/anvils/", 0, 0, filter.clone())],
                "acmeCo/anvils/category=beta/region=eu/pivot=00",
                0,
                vec![],
            ),
            // Partition filter: "alpha" is included, "bad" is excluded.
            (
                vec![("acmeCo/anvils/", 0, 0, filter.clone())],
                "acmeCo/anvils/category=beta/region=bad/pivot=00",
                0,
                vec![],
            ),
        ];

        let mut out = Vec::new();
        for (entries, journal, cohort, expected) in cases {
            let index = HintIndex::new(entries.into_iter());
            index.lookup(&journal, cohort, &mut out).unwrap();
            out.sort();
            assert_eq!(&out, &expected, "journal={journal}, cohort={cohort}");
        }
    }

    fn test_hint_index() -> HintIndex {
        // anvils has 1 partition field ("part"), bananas has 0.
        HintIndex::new(
            [
                ("acmeCo/anvils/", 0, 0, passthrough_filter(&["part"])),
                ("acmeCo/bananas/", 1, 0, passthrough_filter(&[])),
            ]
            .into_iter(),
        )
    }

    #[test]
    fn test_extract_causal_hints_round_trip() {
        let index = test_hint_index();
        let mut causal_hints = CausalHints::default();

        let p1 = producer(0x00);
        let p2 = producer(0x02);

        // Build a transaction with two producers across two journals.
        let txn = vec![
            (
                p1,
                Clock::from_u64(100),
                vec![
                    "acmeCo/anvils/part=a/pivot=00".to_string(),
                    "acmeCo/bananas/pivot=00".to_string(),
                ],
            ),
            (
                p2,
                Clock::from_u64(200),
                vec!["acmeCo/anvils/part=a/pivot=00".to_string()],
            ),
        ];

        let journal_acks = publisher::intents::build_transaction_intents(&txn);

        // For each journal's first ACK, extract hints into causal_hints.
        // build_transaction_intents returns NDJSON bytes per journal;
        // parse the first line back into a serde_json::Value for hint extraction.
        for (journal, ndjson) in &journal_acks {
            let first_line = ndjson.split(|b| *b == b'\n').next().unwrap();
            let ack: serde_json::Value = serde_json::from_slice(first_line).unwrap();
            let uuid_str = ack["_meta"]["uuid"].as_str().unwrap();
            let (ack_producer, commit_clock, _flags) = uuid::parse_str(uuid_str).unwrap();

            extract_causal_hints(
                &index,
                journal,
                0, // cohort
                0, // producing binding (unused: this index has no shared journals)
                ack_producer,
                commit_clock,
                &ack,
                &mut causal_hints,
            )
            .unwrap();
        }

        // Collect into sorted tuples for deterministic assertion.
        let mut entries: Vec<_> = causal_hints
            .iter()
            .map(|((j, b), hints)| {
                let mut h: Vec<_> = hints.iter().map(|(p, c)| (p, c)).collect();
                h.sort();
                (j.as_ref().to_string(), *b, h)
            })
            .collect();
        entries.sort();

        insta::assert_debug_snapshot!(entries);
    }

    #[test]
    fn test_extract_causal_hints_no_hints_and_decode_error() {
        let index = test_hint_index();
        let p1 = producer(0x00);

        // ACK doc without hints field: causal_hints remains empty.
        let mut causal_hints = CausalHints::default();
        let doc = serde_json::json!({"_meta": {"uuid": "00000000-0000-0000-0000-000000000000"}});
        extract_causal_hints(
            &index,
            "acmeCo/anvils/x",
            0,
            0,
            p1,
            Clock::from_u64(100),
            &doc,
            &mut causal_hints,
        )
        .unwrap();
        assert!(causal_hints.is_empty());

        // Malformed hints field: returns decode error.
        let doc = serde_json::json!({"hints": [{"j": "not-an-array", "p": []}]});
        let err = extract_causal_hints(
            &index,
            "acmeCo/anvils/x",
            0,
            0,
            p1,
            Clock::from_u64(100),
            &doc,
            &mut causal_hints,
        )
        .unwrap_err();
        assert!(
            format!("{err}").contains("decoding causal hint"),
            "error should mention decoding: {err}"
        );
    }

    #[test]
    fn test_extract_causal_hints_self_projection() {
        // Common 1:1 case: each journal-prefix maps to one binding → no projection.
        assert!(!test_hint_index().cohort_shares_journal);

        // Two bindings (0, 1) of cohort 0 read the same anvils prefix; binding 2
        // reads a different prefix. Sharing is detected.
        let index = HintIndex::new(
            [
                ("acmeCo/anvils/", 0, 0, passthrough_filter(&["part"])),
                ("acmeCo/anvils/", 1, 0, passthrough_filter(&["part"])),
                ("acmeCo/bananas/", 2, 0, passthrough_filter(&[])),
            ]
            .into_iter(),
        );
        assert!(index.cohort_shares_journal);

        // Same-cohort bindings need not be adjacent under the (prefix, binding)
        // sort: bindings 0 and 2 share the anvils prefix and cohort 0, while
        // binding 1 (cohort 1) sorts between them (priorities `[0, 1, 0]`).
        // Sharing must still be detected.
        let index_interleaved = HintIndex::new(
            [
                ("acmeCo/anvils/", 0, 0, passthrough_filter(&["part"])),
                ("acmeCo/anvils/", 1, 1, passthrough_filter(&["part"])),
                ("acmeCo/anvils/", 2, 0, passthrough_filter(&["part"])),
            ]
            .into_iter(),
        );
        assert!(index_interleaved.cohort_shares_journal);

        let p1 = producer(0x00);
        let mut causal_hints = CausalHints::default();

        // An ACK read by binding 0 from the anvils journal, carrying NO doc hints —
        // exactly the case a single-producer collection ACK presents to a
        // materialization that reads it under two bindings.
        let ack = serde_json::json!({"is_ack": true});
        extract_causal_hints(
            &index,
            "acmeCo/anvils/part=a/pivot=00",
            0, // cohort
            0, // producing binding
            p1,
            Clock::from_u64(100),
            &ack,
            &mut causal_hints,
        )
        .unwrap();

        // The self-hint lands on the *peer* binding (1) that also reads anvils —
        // never on the producing binding (0), nor on the unrelated bananas
        // binding (2). So the checkpoint can't advance binding 0 past this commit
        // until binding 1's read of anvils also reaches it.
        let entries: Vec<_> = causal_hints
            .iter()
            .map(|((j, b), hints)| (j.as_ref().to_string(), *b, hints.clone()))
            .collect();
        assert_eq!(
            entries,
            vec![(
                "acmeCo/anvils/part=a/pivot=00".to_string(),
                1u16,
                vec![(p1, Clock::from_u64(100))],
            )],
        );
    }
}
